README.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

@frankwiles Since all TestCase.get/post() kwargs (except 'data') were passed to reverse(), there was no way to pass kwargs to self.client.get/post(). This problem appeared for me when trying to set HTTP_X_REQUESTED_WITH.
This might improve test coverage as well, for TestCase.post().

Adding 'extra' param for self.client.get/post kwargs.

---

test_plus/test.py
test_project/test_app/tests.py

The login class always used "password" when the initial argument was a User instance. This fix updates login class to use the specified password (if provided!) when initial argument is a User. If no password is provided in credentials then "password" is still used by default.
In order to test this, TestCase.make_user() also needed a default password argument, which is probably a Good Thing in any case.

Honor password when passing User to login class

---

test_plus/test.py
test_project/test_app/tests.py

This makes it easy to add user permissions to a test user. I know in issue #8 you said you didn't think it was generic enough, but then I thought about it and changed it to a ``perms`` argument instead, which I think is better and makes it so it could work for everyone. I could also add some docs if you want.

Added the perms argument to the make_user method

---

README.rst
test_plus/test.py
test_project/test_app/templates/other.html
test_project/test_app/templates/test.html
test_project/test_app/tests.py
test_project/test_app/views.py

For generic view unit testing, rather than use MyClass.as_view(), CBVTestCase allows instantiation of a generic view class for testing class methods.
Django's generic View.as_view() invokes URL resolvers and middleware, both of which are often not needed for testing class methods. Use CBVTestCase.get_instance() to obtain an initialized instance of your class, then test the class methods as desired.
View.get() and .post() methods are provided for CBVs, and both work with existing django-test-plus TestCase assertion methods.

Adding test methods and utilities for class-based views

---

AUTHORS.txt
CHANGELOG.txt
README.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

It is not unusual when writing Django tests to use the `follow` argument. While this is especially common when writing `POST` tests for forms, it can also occur with `GET` tests. What this pull request does is add this argument (defaulting to `False`) and then pass it along to the underlying test methods.

Adds the follow argument to get and post

---

test_plus/test.py

This is an IDE convenience + enhancement.
PyCharm is getting confused and reimporting the Django TestCase class; meaning no autocomplete and unresolved reference warnings.  It's no fun.  The proposed change fixes the problem with minimal impact.
Also, it's sort of a sloppy naming convention as is.

Alias Django's TestCase

---

requirements-dev.txt

Quick fix for a typo (I believe - I could not find the listed package on PyPI).

Fix pypandoc requirement typo.

---

.travis.yml
test_plus/test.py
tox.ini

The library used to make the assumption that the `USERNAME_FIELD` was always going to be `username` however this is easily overloaded.
This allows testing of the following form:
class MyTest(TestCase):
user_factory = MyUserFactory
def test_some_feature(self):
u1 = self.make_user()
self.login(u1):
self.assertTrue(True)
Assuming custom User model, such as:
class User(AbstractBaseUser, PermissionsMixin):
email = EmailField(
verbose_name='email address',
max_length=255,
unique=True,
)
USERNAME_FIELD = 'email'

Introspect the USERNAME_FIELD on custom User models

---

CHANGELOG.txt
test_plus/test.py

This fixes #28. Ran into the same issue today and noticed a solution.

Fixed assertLoginRequired when settings.LOGIN_URL is a named URL pattern

---

.gitignore
test_plus/test.py
test_project/test_app/tests.py

I love using `self.get()` syntax and therefore want more such functionality. So added other methods like `put`, `patch`, `options`, `delete`, `trace`, `head`.

Add support for more than two (get, post) http methods.

---

.travis.yml
docs/methods.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py
tox.ini

A couple of convenience methods to save some typing in test cases.
def test_response_contains(self):
self.get('hello-world')
self.assertResponseContains('<p>Hello, World!</p>')
def test_response_not_contains(self):
self.get('hello-world')
self.assertResponseNotContains('<p>Hello, Frank!</p>')
Uses the private _which_response method and defaults html to True.

Add assertResponseContains & assertResponseNotContains methods

---

docs/methods.rst
test_plus/test.py
test_project/runtests.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

Not a particularly exciting addition, but I have a need to check a view that returns a HttpResponsePermanentRedirect response so decided to add provide this for parity with 302.

Add response_301 method to check for django.http.HttpResponsePermanentRedirect

---

docs/cbvtestcase.rst
test_plus/test.py
test_project/test_app/forms.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

This update refactors CBVTestCase.get_instance(), .get(), and .post() in order to allow use of custom Request objects in CBVTestCase.get() and .post().
Often a view method needs to reference `request.user` or some other special attribute. Now testers can create a request from RequestFactory, assign the attribute(s) needed, and pass the request to .get() or .post().
This PR does not change current behavior. If no `request` is passed to .get() or .post(), an empty Request instance is created and used just like before.

Allow custom Request for CBVTestCase.get(), .post()

---

.travis.yml
requirements-dev.txt
requirements-travisci.txt
requirements.txt
tox.ini

Since Python 3.3 is no longer maintained and it's usage is next to nothing, we might as well speed up our test suite by dropping support for it. See notes here for how small it's usage was a year+ ago: https://github.com/pypa/pip/issues/3796

:fire: Drop Python 3.3 Support

---

.travis.yml
README.rst
docs/low_query_counts.rst
docs/methods.rst
requirements.txt
setup.py
test_plus/compat.py
test_plus/runner.py
test_plus/test.py
test_project/test_app/tests.py
test_project/test_project/settings.py
tox.ini

In theory, nothing has changed which will prevent older versions from working internally. However, we want to set a reasonable standard for which versions to update for yet keep our testsuite running quickly. 
Fixes #62

:fire: Drop Django <1.8 support

---

.travis.yml
test_plus/compat.py
test_project/test_app/views.py
test_project/test_project/settings.py
tox.ini

Re-opened solution for #65.
After realising why things were failing in travis (exclusion was not working as expected) I decided to substitute defining the build matrix in `.travis.yml` and instead defer that duty to `tox`.
There is (demonstrably) a maintenance burden associated with making travis play nicely with what is already defined in `tox.ini`. Applying DRY to the CI seems like the right thing to do to solve that, and it shouldn't result in any surprises for the next developer who has locally run the test suite with a success, only to have it fail in travis.

Really test Django 2.0

---

.travis.yml
tox.ini

Any reason not to? I don't use `pypy` much myself, but since the build is currently passing it seems like a good time to declare support for it.

Add pypy testing

---

README.md
docs/methods.rst

Closes #104 
Based on this PR: https://github.com/revsys/django-test-plus/commit/abb8a252f14d9546d7ef79fc75cbbc1108d24878, I added the list of `response_NNN` methods back to the README. I also found the right spot in `methods.rst` and added the same text there.

Add response_### methods back to docs

---

test_plus/test.py

The `django.utils.functional.curry` function has been removed in favour of using `functools.partial` or `functools.partialmethod` as appropriate.

Django 3.0+ support

---

.travis.yml
setup.py
tox.ini

Updates tests, setup.py, and CI to fully test Django 2.2, 3.0, and Python 3.8. 
Related to #113 and #110

:arrow_up: Bumps tests for Django 3.0

---

requirements.in
requirements.txt
setup.py
tox.ini

Bumps project up to support Django 3.2. 
In theory, this as already done with the `latest` check, but fixes trove classifiers, etc.

:arrow_up: Bumps project up to Django 3.2

---

docs/cbvtestcase.rst

Two code block examples are not recognized as code blocks because they have two levels of indent:
This PR _should_ fix that formatting by removing one level of indent. Although I haven't seen the result rendered locally (just on github, "View file"), I'm following the same convention seen in the rest of DTP documentation, one level of indent.
I didn't add the ReST code-block syntax since the existing DTP documentation does not use that format.
```
..  code-block:: php
```
The result:

Fix CBVTest example code block indentation

---

.github/workflows/actions.yml

We might add an extra test to test some of the older versions but this is fine for now.

:fire: Only test latest DRF to avoid ~200 extra runners

---

.github/workflows/actions.yml
test_plus/test.py
test_project/test_app/tests/test_unittests.py

Ok, I think this should handle the core part of #81. If I'm understanding the code correctly, the new `APITestCase.request()` method should be converting the `kwargs` data into JSON, and the `post/put/get/delete` methods are using that `request` method, so that should be doing what we want.
I'm not entirely clear on the `"HTTP_X_REQUESTED_WITH": "XMLHttpRequest"` bit, but it seems to be required for AJAXy stuff, at least according to [this](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX). But when I try to find it in the Django docs, the latest thing I see is something that was [deprecated in 3.1
](https://docs.djangoproject.com/en/4.1/releases/3.1/#id2)
I'm still looking into the `With an easy way to pass in headers like Authorization and Token stuff` part. I'm not great with …

APITestcase object requests should default to JSON

---

README.md

Hi, I noticed that 4.2 was missing from the supported versions list on the README, I hope you don't mind this pull request.

⬆️ Add Django 4.2 to supported versions in README

---

test_plus/test.py

Allow creation of User instances even when the model does not support `username`

---

test_plus/test.py

Including:
* Use `assertIn` which produces a clearer message on error.
* Reuse `get_context` in `assertContext` and `assertInContext`.
* Move `assertInContext` closer to `get_context` and `assertContext`.
* Extend query counter `assertNumQueriesLessThan` to show executed queries.

Assorted fixes following usage of the utilities.

---

pytest.ini
setup.cfg

This is added in Pytest 7
Fixes my failure to locally CI as mentioned in https://github.com/revsys/django-test-plus/pull/210#issuecomment-2081532869

Use pytest's native python path support

---

.github/workflows/actions.yml
noxfile.py
setup.cfg
test_plus/test.py

Fixes: https://github.com/revsys/django-test-plus/issues/209

Use packaging.version where available

---

test_plus/test.py
test_project/test_app/tests/test_unittests.py
test_project/test_app/views.py
test_project/test_project/settings.py

It's an attempt to fix bug reported in #205 
It's been introduced in #190  
I've looked into it.
Changes i've introduced:
- added tests for GET requests
- corrected existing tests for POST requests (`format` and `content_type` options were used incorrectly)
- removed `APITestCase.request` as it's redundant. In #81 the solution should be to recommend users to set default format in tests. [DRF docs](https://www.django-rest-framework.org/api-guide/testing/#setting-the-default-format)
All changes are explained in commit messages.
All nox tests pass locally.

Revert `APITestCase` defaulting to JSON format.

---

.github/workflows/actions.yml
README.md
noxfile.py
setup.cfg
test_project/test_project/settings.py

Upgrades all the things to Django 5.1.

:arrow_up: Adds support for Django 5.1
