test_plus/test.py

This makes it so you can just simply type ``self.make_user()``, which is usually what you want.

Added the default 'testuser' for the username

---

.gitignore
README.rst
test_plus/test.py

Updating documentation for code in v1.0.5, specifically the make_user() method.
Also added "*.pyc" to the .gitignore file.

Update documentation for v1.0.5

---

README.rst
test_plus/runner.py
test_project/test_project/settings.py

This adds a new TestRunner that disables logging during your testing.

Adds a new TestRunner that disables logging

---

.travis.yml
test_plus/__init__.py
test_plus/test.py
test_project/runtests.py
test_project/test_app/urls.py
test_project/test_project/settings.py

Feel free to use this if you want. I find it helpful to have this in my projects.

Added flake8 and testing with flake8 in shippable.

---

README.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

Adds support for an HTTP 405 response test.

Add test for HTTP 405 response.

---

docs/methods.rst

Fixing the documentation to match the method signatures.

Fixing documentation for get and post methods.

---

docs/methods.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

Test for use of HttpResponseGone responses.

Add response_410 method

---

test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

I have a need to check for a 401 status code in my response.
Includes tests.

Add check for 401 response status_code

---

docs/low_query_counts.rst

simple correction to this awesome package

removing double "generates"

---

docs/methods.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

Status code 400 (Bad Request) is very common, and I need checks for it.
Thanks for maintaining the project!

Add check for status code 400 (Bad Request)

---

README.rst
test_plus/test.py
test_project/test_app/forms.py
test_project/test_app/templates/form_errors.html
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

This should be pretty much ready to merge, except I haven't added any documentation yet.
This PR is related to issue #46.

Added the print_form_errors utility

---

docs/methods.rst
test_plus/test.py
test_project/test_app/tests.py
test_project/test_app/urls.py
test_project/test_app/views.py

New assertion that allows checking of `HttpResponse` headers.

Add assertResponseHeaders

---

AUTHORS.txt
docs/methods.rst

When reading the docs I noticed a couple small errors.

:pencil: Small grammatical fixes

---

README.md
docs/methods.rst
test_plus/test.py

Closes https://github.com/revsys/django-test-plus/issues/75

Add message field to response_xxx methods

---

test_plus/plugin.py

Add optional `msg` argument to assertEqual method

---

requirements.txt
setup.py

This is a fix for @dependabot's update (jerk)

:arrow_down: Downgrade pytest to support 2.7 :roll_eyes:

---

requirements.txt
setup.py

⬆️ Updates requirements

---

setup.py
tox.ini

Boring up date that adds Python 3.9 to test against and our trover classifier.

:arrow_up: :snake: Adds Python 3.9 to matrix

---

README.md

Add pypi badge to README.md

---

test_plus/plugin.py
test_project/test_app/tests/test_pytest.py

:green_heart: Fixes missing Django assert classes

---

requirements.txt

Our goal here is to silence to CVE warning messages.

:arrow_up: Upgrade project deps

---

.github/workflows/actions.yml

:hammer: Fixes GitHub Actions runners

---

.github/workflows/actions.yml
setup.cfg

Still, WIP(y) while I work out if it's worth dropping tox for nox which I already like it better. 
https://hynek.me/articles/why-i-like-nox/

:arrow_up: Adds py3.11 support
